#!/usr/bin/env python

from time import sleep
import os
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(23,GPIO.IN)
GPIO.setup(24,GPIO.IN)
GPIO.setup(25,GPIO.IN)

while True:
	if ( GPIO.input(23) == False ):
		os.system('omxplayer /home/pi/Desktop/archivos/testmp4.mp4')
	sleep(1)


